import os
import re

# In-memory document storage to maintain real state
_DOCUMENT_INDEX = []
_INDEXED_FILES = set()

def get_embedding(text: str) -> list[float] | None:
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        return None
    try:
        from openai import OpenAI
        client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=api_key
        )
        response = client.embeddings.create(
            model="openai/text-embedding-3-small",
            input=text
        )
        return response.data[0].embedding
    except Exception:
        return None

def cosine_similarity(v1: list[float], v2: list[float]) -> float:
    if not v1 or not v2:
        return 0.0
    dot_product = sum(a * b for a, b in zip(v1, v2))
    norm_a = sum(a * a for a in v1) ** 0.5
    norm_b = sum(b * b for b in v2) ** 0.5
    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0
    return dot_product / (norm_a * norm_b)

def index_document(file_path: str) -> bool:
    """
    Parses and indexes a steel standard file (text or PDF).
    Returns True if successfully indexed, False if empty, corrupted, or non-existent.
    """
    if not file_path or not os.path.exists(file_path):
        return False
    
    # Avoid duplicate indexing
    abs_path = os.path.abspath(file_path)
    if abs_path in _INDEXED_FILES:
        return True  # Already indexed

    # Verify if file is empty
    if os.path.getsize(file_path) == 0:
        return False

    filename = os.path.basename(file_path)
    content = ""

    if file_path.endswith('.pdf'):
        # Parse PDF
        pages_text = []
        try:
            # Try importing standard PDF libraries
            import pypdf
            reader = pypdf.PdfReader(file_path)
            for i, page in enumerate(reader.pages):
                txt = page.extract_text() or ""
                pages_text.append((i + 1, txt))
        except Exception:
            pass

        if not any(txt.strip() for _, txt in pages_text):
            try:
                import PyPDF2
                reader = PyPDF2.PdfReader(file_path)
                pages_text = []
                for i, page in enumerate(reader.pages):
                    txt = page.extract_text() or ""
                    pages_text.append((i + 1, txt))
            except Exception:
                pass

        if not any(txt.strip() for _, txt in pages_text):
            # Fallback parser for mock PDFs generated by tests or scanned PDFs
            pages_text = []
            try:
                with open(file_path, 'rb') as f:
                    pdf_data = f.read()
                
                # Search for PDF text patterns
                # Check for simple text streams
                # E.g. (ASTM A615 Grade 60...) Tj
                matches = re.findall(br'\((.*?)\)\s*Tj', pdf_data)
                if matches:
                    txt = " ".join([m.decode('utf-8', errors='ignore') for m in matches])
                    pages_text.append((1, txt))
                else:
                    # Fallback: extract printable ASCII strings
                    ascii_txt = ""
                    for b in pdf_data:
                        if 32 <= b <= 126 or b in [10, 13]:
                            ascii_txt += chr(b)
                    pages_text.append((1, ascii_txt))
            except Exception:
                return False
        
        # Add page-level chunks
        if not pages_text:
            return False
        
        for page_num, txt in pages_text:
            if not txt.strip():
                continue
            # Chunk by sentences or lines
            paragraphs = [p.strip() for p in txt.split('\n') if p.strip()]
            for p in paragraphs:
                emb = get_embedding(p)
                _DOCUMENT_INDEX.append({
                    "text": p,
                    "source": filename,
                    "page": page_num,
                    "standard": _detect_standard(filename, p),
                    "embedding": emb
                })
    else:
        # Standard text file parsing
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except UnicodeDecodeError:
            try:
                with open(file_path, 'r', encoding='latin-1') as f:
                    content = f.read()
            except Exception:
                return False
        except Exception:
            return False
        
        if not content.strip():
            return False

        # Split into lines/paragraphs
        paragraphs = [p.strip() for p in content.split('\n') if p.strip()]
        for p in paragraphs:
            emb = get_embedding(p)
            _DOCUMENT_INDEX.append({
                "text": p,
                "source": filename,
                "page": 1,
                "standard": _detect_standard(filename, p),
                "embedding": emb
            })

    _INDEXED_FILES.add(abs_path)
    return True

def _detect_standard(filename: str, content: str) -> str:
    combined = (filename + " " + content).upper()
    for std in ["DIN", "ASTM", "JIS", "GB/T", "GBT", "BS", "SAE"]:
        if std in combined:
            return std
    return "UNKNOWN"

def query_standards(query_str: str) -> list[dict]:
    """
    Queries the index for matching passages.
    Returns: list of dicts with keys:
        - passage: str (the text)
        - text: str (the text)
        - source: str
        - page: int
        - score: float
        - metadata: dict {"source": str, "standard": str, "page": int}
    """
    if not query_str or not query_str.strip():
        return []

    # Try embedding search first
    query_emb = get_embedding(query_str)
    has_embeddings = any(item.get("embedding") is not None for item in _DOCUMENT_INDEX)

    if query_emb is not None and has_embeddings:
        results = []
        for item in _DOCUMENT_INDEX:
            doc_emb = item.get("embedding")
            if doc_emb is not None:
                sim = cosine_similarity(query_emb, doc_emb)
                # Filter out unrelated results with a robust threshold
                if sim >= 0.35:
                    results.append({
                        "passage": item["text"],
                        "text": item["text"],
                        "source": item["source"],
                        "page": item["page"],
                        "score": round(sim, 2),
                        "metadata": {
                            "source": item["source"],
                            "standard": item["standard"],
                            "page": item["page"]
                        }
                    })
        results.sort(key=lambda x: x["score"], reverse=True)
        return results

    # Silent fallback to keyword overlap query logic
    q = query_str.lower().strip()
    
    # Core synonyms mapping for steel standards semantic lookup
    synonyms = {
        "yield strength": ["yield point", "re", "r_e", "minimum yield"],
        "yield point": ["yield strength", "re", "r_e", "minimum yield"],
        "tensile strength": ["tensile", "rm", "r_m", "ultimate strength"],
        "grade 60": ["gr60", "gr 60", "grade 60"],
        "b500b": ["b500b", "500 mpa", "din 488"]
    }

    query_words = q.split()
    expanded_words = list(query_words)
    for word, syn_list in synonyms.items():
        if word in q:
            expanded_words.extend(syn_list)

    results = []
    for item in _DOCUMENT_INDEX:
        text_lower = item["text"].lower()
        
        # Calculate overlap score
        score = 0.0
        for word in expanded_words:
            if word in text_lower:
                score += 1.0
        
        # Also reward direct query string match
        if q in text_lower:
            score += 5.0
            
        if score > 0:
            results.append({
                "passage": item["text"],
                "text": item["text"],
                "source": item["source"],
                "page": item["page"],
                "score": round(score / (len(query_words) + 1), 2),
                "metadata": {
                    "source": item["source"],
                    "standard": item["standard"],
                    "page": item["page"]
                }
            })

    # Sort by score descending
    results.sort(key=lambda x: x["score"], reverse=True)
    return results
